# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lint.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "lint.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nlint.proto\x12\x04lint"\x84\x01\n\x0bLintRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\tlintFiles\x18\x02 \x03(\x0b\x32\x0e.lint.LintFile\x12 \n\x08lintMeta\x18\x03 \x01(\x0b\x32\x0e.lint.LintMeta\x12"\n\tlintPatch\x18\x04 \x01(\x0b\x32\x0f.lint.LintPatch")\n\x08LintFile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c")\n\x08LintMeta\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c"*\n\tLintPatch\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c"@\n\tLintReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x0blintReports\x18\x02 \x03(\x0b\x32\x10.lint.LintReport"G\n\nLintReport\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t2=\n\tLintProto\x12\x30\n\x08SendLint\x12\x11.lint.LintRequest\x1a\x0f.lint.LintReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "lint_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LINTREQUEST"]._serialized_start = 21
    _globals["_LINTREQUEST"]._serialized_end = 153
    _globals["_LINTFILE"]._serialized_start = 155
    _globals["_LINTFILE"]._serialized_end = 196
    _globals["_LINTMETA"]._serialized_start = 198
    _globals["_LINTMETA"]._serialized_end = 239
    _globals["_LINTPATCH"]._serialized_start = 241
    _globals["_LINTPATCH"]._serialized_end = 283
    _globals["_LINTREPLY"]._serialized_start = 285
    _globals["_LINTREPLY"]._serialized_end = 349
    _globals["_LINTREPORT"]._serialized_start = 351
    _globals["_LINTREPORT"]._serialized_end = 422
    _globals["_LINTPROTO"]._serialized_start = 424
    _globals["_LINTPROTO"]._serialized_end = 485
# @@protoc_insertion_point(module_scope)
