apiVersion: v1
kind: worker
metadata:
  name: lintwork
spec:
  lintai:
    lintgpt:
  lintcpp:
    cpplint:
  lintjava:
    aosplint:
      - --disable
      - LintError
      - --nolines
      - --quiet
    checkstyle:
      - -jar
      - /home/craftslab/opt/checkstyle/lib/checkstyle.jar
      - -c=/home/craftslab/opt/checkstyle/etc/google_checks.xml
    javalint:
      - -jar
      - /home/craftslab/opt/javalint/lib/javalint.jar
      - --file
    stringscheck:
  lintkernel:
    checkpatch:
      - --no-summary
      - --no-tree
      - --terse
  lintmake:
    checkmake:
      - --format=:{{.LineNumber}}::{{.Violation}}\n
  lintpython:
    flake8:
  lintshell:
    shellcheck:
      - --format=gcc
